/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    index: Index;
    about: About;
    'blog-page': BlogPage;
    footer: Footer;
    links: Link;
  };
  globalsSelect: {
    index: IndexSelect<false> | IndexSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'user' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  slug: string;
  heading: string;
  subheading: string;
  brief: string;
  publishedDate: string;
  paragraph1?: string | null;
  paragraph2?: string | null;
  paragraph3?: string | null;
  paragraph4?: string | null;
  image1?: (number | null) | Media;
  image2?: (number | null) | Media;
  image3?: (number | null) | Media;
  video?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T;
  heading?: T;
  subheading?: T;
  brief?: T;
  publishedDate?: T;
  paragraph1?: T;
  paragraph2?: T;
  paragraph3?: T;
  paragraph4?: T;
  image1?: T;
  image2?: T;
  image3?: T;
  video?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index".
 */
export interface Index {
  id: number;
  overlay?: {
    title?: string | null;
    subtitle?: string | null;
  };
  hero: {
    title?: string | null;
    videos: {
      video?: (number | null) | Media;
      id?: string | null;
    }[];
  };
  trailers?: {
    title?: string | null;
    trailer?:
      | {
          trailerTitle?: string | null;
          image?: (number | null) | Media;
          link?: string | null;
          categories: {
            category: 'favourites' | 'international' | 'celebrities' | 'classics';
          };
          id?: string | null;
        }[]
      | null;
    next?: string | null;
  };
  map?: {
    sectionHeader?: string | null;
    mapHeader?: string | null;
    locations?:
      | {
          city?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    mapParagraph?: string | null;
    highlightImages?:
      | {
          image?: (number | null) | Media;
          heading?: string | null;
          paragraph?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  workSummary?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  presentStatistic?: {
    title?: string | null;
    caption?: string | null;
    video?: (number | null) | Media;
    statistics?:
      | {
          label?: string | null;
          value?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    title?: string | null;
    subtitle?: string | null;
    reviews?:
      | {
          author?: string | null;
          designation?: string | null;
          review?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  quoteImage?: {
    image?: (number | null) | Media;
  };
  GIFImage?: {
    image?: (number | null) | Media;
    caption?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero?: {
    title?: string | null;
    image?: (number | null) | Media;
    logo?: (number | null) | Media;
    nav?:
      | {
          text?: string | null;
          'link to'?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  founder?: {
    heading?: string | null;
    founders?:
      | {
          image?: (number | null) | Media;
          name?: string | null;
          designation?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  story?: {
    heading?: string | null;
    image?: (number | null) | Media;
    paragraph?: string | null;
  };
  team?: {
    heading?: string | null;
    members?:
      | {
          name?: string | null;
          image?: (number | null) | Media;
          role?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  reviews?: {
    heading?: string | null;
    cards?:
      | {
          image?: (number | null) | Media;
          review?: string | null;
          name?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  heading: string;
  subheading: string;
  image: number | Media;
  video: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  mainText: string;
  logo?: (number | null) | Media;
  links?:
    | {
        placeholder: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  Facebook: string;
  Instagram: string;
  Twitter: string;
  Whatsapp: string;
  Youtube: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index_select".
 */
export interface IndexSelect<T extends boolean = true> {
  overlay?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        videos?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  trailers?:
    | T
    | {
        title?: T;
        trailer?:
          | T
          | {
              trailerTitle?: T;
              image?: T;
              link?: T;
              categories?:
                | T
                | {
                    category?: T;
                  };
              id?: T;
            };
        next?: T;
      };
  map?:
    | T
    | {
        sectionHeader?: T;
        mapHeader?: T;
        locations?:
          | T
          | {
              city?: T;
              latitude?: T;
              longitude?: T;
              link?: T;
              id?: T;
            };
        mapParagraph?: T;
        highlightImages?:
          | T
          | {
              image?: T;
              heading?: T;
              paragraph?: T;
              id?: T;
            };
      };
  workSummary?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  presentStatistic?:
    | T
    | {
        title?: T;
        caption?: T;
        video?: T;
        statistics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        title?: T;
        subtitle?: T;
        reviews?:
          | T
          | {
              author?: T;
              designation?: T;
              review?: T;
              image?: T;
              id?: T;
            };
      };
  quoteImage?:
    | T
    | {
        image?: T;
      };
  GIFImage?:
    | T
    | {
        image?: T;
        caption?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        image?: T;
        logo?: T;
        nav?:
          | T
          | {
              text?: T;
              'link to'?: T;
              id?: T;
            };
      };
  founder?:
    | T
    | {
        heading?: T;
        founders?:
          | T
          | {
              image?: T;
              name?: T;
              designation?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        heading?: T;
        image?: T;
        paragraph?: T;
      };
  team?:
    | T
    | {
        heading?: T;
        members?:
          | T
          | {
              name?: T;
              image?: T;
              role?: T;
              id?: T;
            };
      };
  reviews?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              image?: T;
              review?: T;
              name?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  image?: T;
  video?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  mainText?: T;
  logo?: T;
  links?:
    | T
    | {
        placeholder?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  Facebook?: T;
  Instagram?: T;
  Twitter?: T;
  Whatsapp?: T;
  Youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}